// Package kube writes per-context kubeconfig files whose credentials always
// come from mek (`mek --context <ctx> kube token ...`), so kubectl, K9s and
// FreeLens use the context's cloud login and never a stored key.
package kube

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"maps"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"

	"github.com/goccy/go-yaml"

	"github.com/prateep-r/mek/internal/config"
	"github.com/prateep-r/mek/internal/fsutil"
	"github.com/prateep-r/mek/internal/provider"
)

// Dir holds mek's kubeconfig files.
func Dir() string { return filepath.Join(config.Dir(), "kube") }

// Path is the kubeconfig file of one context.
func Path(ctx string) string { return filepath.Join(Dir(), ctx+".yaml") }

// Env returns the KUBECONFIG a context's commands get: its mek kubeconfig,
// when the context has clusters or the file was generated before.
func Env(ctx *config.Context) (string, bool) {
	p := Path(ctx.Name)
	if len(ctx.Clusters) > 0 {
		return p, true
	}
	_, err := os.Stat(p)
	return p, err == nil
}

// Owned reports whether a KUBECONFIG value is mek's alone (every path in
// mek's directory), so mek may replace or unset it; a list the user built
// with mek's file in it stays theirs.
func Owned(kubeconfig string) bool {
	paths := filepath.SplitList(kubeconfig)
	for _, p := range paths {
		if !owned(p) {
			return false
		}
	}
	return len(paths) > 0
}

func owned(p string) bool { return strings.HasPrefix(p, Dir()+string(filepath.Separator)) }

// Test seams.
var (
	executable = os.Executable
	lookPath   = exec.LookPath
)

// MekPath is the mek the kubeconfig's exec plugin runs: the one on PATH when
// it is the running binary (a stable Homebrew symlink beats the versioned
// Caskroom path), else the running binary itself.
func MekPath() (string, error) {
	exe, err := executable()
	if err != nil {
		return "", err
	}
	if p, err := lookPath("mek"); err == nil {
		a, aerr := os.Stat(p)
		b, berr := os.Stat(exe)
		if aerr == nil && berr == nil && os.SameFile(a, b) {
			return p, nil
		}
	}
	return exe, nil
}

// Entry is one cluster in a context's kubeconfig.
type Entry struct {
	Alias   string
	Cluster config.Cluster
	Info    provider.KubeCluster
}

// Name is the cluster's name in kubeconfig files: unique across contexts.
func (e Entry) Name(ctx string) string { return ctx + "/" + e.Alias }

// tokenArgs are the exec plugin arguments: the cluster's real identity, so
// ad-hoc clusters work and renaming an alias doesn't break a file.
func (e Entry) tokenArgs(ctx string) []string {
	return []string{"--context", ctx, "kube", "token", "--name", e.Cluster.Name, "--location", e.Info.Location}
}

// Describe looks up every cluster (sorted by alias) through the provider.
func Describe(kp provider.KubeProvider, clusters map[string]*config.Cluster, q provider.Query) ([]Entry, error) {
	var entries []Entry
	for _, alias := range slices.Sorted(maps.Keys(clusters)) {
		info, err := kp.DescribeCluster(*clusters[alias], q)
		if err != nil {
			return nil, fmt.Errorf("cluster %s: %w", alias, err)
		}
		entries = append(entries, Entry{Alias: alias, Cluster: *clusters[alias], Info: info})
	}
	return entries, nil
}

// Write renders entries into the context's kubeconfig — the fixed skeleton of
// the Template Method; Describe's provider supplied the cloud-specific parts.
// current selects current-context (default: the first entry).
func Write(ctx string, entries []Entry, current, mek, pathEnv string) (string, error) {
	b, err := Render(ctx, entries, current, mek, pathEnv)
	if err != nil {
		return "", err
	}
	p := Path(ctx)
	return p, fsutil.WriteFileAtomic(p, b, 0o600)
}

// Render produces the kubeconfig YAML.
func Render(ctx string, entries []Entry, current, mek, pathEnv string) ([]byte, error) {
	if len(entries) == 0 {
		return nil, fmt.Errorf("no clusters to write")
	}
	cfg := kubeconfig{APIVersion: "v1", Kind: "Config", CurrentContext: entries[0].Name(ctx), Preferences: map[string]any{}}
	for _, e := range entries {
		name := e.Name(ctx)
		if e.Alias == current {
			cfg.CurrentContext = name
		}
		cfg.Clusters = append(cfg.Clusters, namedCluster{name, clusterInfo{e.Info.Server, e.Info.CAData}})
		cfg.Users = append(cfg.Users, namedUser{name, userInfo{execConfig{
			APIVersion: "client.authentication.k8s.io/v1beta1", Command: mek, Args: e.tokenArgs(ctx),
			Env: []execEnv{{"PATH", pathEnv}}, InteractiveMode: "Never",
			InstallHint: "mek is needed for these credentials: https://github.com/prateep-r/mek",
		}}})
		cfg.Contexts = append(cfg.Contexts, namedContext{name, contextInfo{name, name, e.Cluster.Namespace}})
	}
	var buf bytes.Buffer
	buf.WriteString("# Generated by mek — `mek -c " + ctx + " kube` rewrites it.\n")
	out, _ := yaml.Marshal(cfg) // plain structs of strings always marshal
	buf.Write(out)
	return buf.Bytes(), nil
}

type kubeconfig struct {
	APIVersion     string         `yaml:"apiVersion"`
	Kind           string         `yaml:"kind"`
	Clusters       []namedCluster `yaml:"clusters"`
	Users          []namedUser    `yaml:"users"`
	Contexts       []namedContext `yaml:"contexts"`
	CurrentContext string         `yaml:"current-context"`
	Preferences    map[string]any `yaml:"preferences"`
}
type namedCluster struct {
	Name    string      `yaml:"name"`
	Cluster clusterInfo `yaml:"cluster"`
}
type clusterInfo struct {
	Server string `yaml:"server"`
	CAData string `yaml:"certificate-authority-data,omitempty"`
}
type namedUser struct {
	Name string   `yaml:"name"`
	User userInfo `yaml:"user"`
}
type userInfo struct {
	Exec execConfig `yaml:"exec"`
}
type execConfig struct {
	APIVersion         string    `yaml:"apiVersion"`
	Command            string    `yaml:"command"`
	Args               []string  `yaml:"args"`
	Env                []execEnv `yaml:"env"`
	InteractiveMode    string    `yaml:"interactiveMode"`
	ProvideClusterInfo bool      `yaml:"provideClusterInfo"`
	InstallHint        string    `yaml:"installHint"`
}
type execEnv struct {
	Name  string `yaml:"name"`
	Value string `yaml:"value"`
}
type namedContext struct {
	Name    string      `yaml:"name"`
	Context contextInfo `yaml:"context"`
}
type contextInfo struct {
	Cluster   string `yaml:"cluster"`
	User      string `yaml:"user"`
	Namespace string `yaml:"namespace,omitempty"`
}

// MergeTarget is the kubeconfig `mek kube --merge` edits: the first file of
// $KUBECONFIG that isn't mek's own, else ~/.kube/config.
func MergeTarget(kubeconfigEnv, home string) string {
	for _, p := range filepath.SplitList(kubeconfigEnv) {
		if p != "" && !owned(p) {
			return p
		}
	}
	return filepath.Join(home, ".kube", "config")
}

// MergeCommands builds the official `kubectl config` commands (Command +
// Builder) that add entries to target — kubectl merges and keeps everything
// else. caFile writes each CA to a file, since kubectl embeds certificates
// from files.
func MergeCommands(ctx, target string, entries []Entry, mek, pathEnv string, use bool, caFile func(Entry) (string, error)) ([][]string, error) {
	var cmds [][]string
	cfg := func(args ...string) {
		cmds = append(cmds, append(append([]string{"kubectl", "config"}, args...), "--kubeconfig", target))
	}
	for _, e := range entries {
		name := e.Name(ctx)
		ca, err := caFile(e)
		if err != nil {
			return nil, err
		}
		cfg("set-cluster", name, "--server="+e.Info.Server, "--certificate-authority="+ca, "--embed-certs=true")
		user := []string{"set-credentials", name, "--exec-api-version=client.authentication.k8s.io/v1beta1",
			"--exec-command=" + mek, "--exec-env=PATH=" + pathEnv, "--exec-interactive-mode=Never"}
		for _, a := range e.tokenArgs(ctx) {
			user = append(user, "--exec-arg="+a)
		}
		cfg(user...)
		setCtx := []string{"set-context", name, "--cluster=" + name, "--user=" + name}
		if e.Cluster.Namespace != "" {
			setCtx = append(setCtx, "--namespace="+e.Cluster.Namespace)
		}
		cfg(setCtx...)
	}
	if use {
		cfg("use-context", entries[0].Name(ctx))
	}
	return cmds, nil
}

// UnmergeCommands removes what MergeCommands added (the reverse commands).
func UnmergeCommands(ctx, target string, aliases []string) [][]string {
	var cmds [][]string
	for _, alias := range aliases {
		name := ctx + "/" + alias
		for _, del := range []string{"delete-context", "delete-cluster", "delete-user"} {
			cmds = append(cmds, []string{"kubectl", "config", del, name, "--kubeconfig", target})
		}
	}
	return cmds
}

// WriteCA decodes an entry's CA into dir for `kubectl config set-cluster`.
func WriteCA(dir string, e Entry) (string, error) {
	pem, err := base64.StdEncoding.DecodeString(e.Info.CAData)
	if err != nil {
		return "", fmt.Errorf("cluster %s: certificate-authority-data: %w", e.Alias, err)
	}
	p := filepath.Join(dir, e.Alias+".crt")
	return p, os.WriteFile(p, pem, 0o600)
}

// Backup copies target to target.mek-backup once, before mek first edits it.
func Backup(target string) error {
	b, err := os.ReadFile(target)
	if os.IsNotExist(err) {
		return nil // nothing to keep
	}
	if err != nil {
		return err
	}
	backup := target + ".mek-backup"
	if _, err := os.Stat(backup); err == nil {
		return nil
	}
	return os.WriteFile(backup, b, 0o600)
}
