package provider

import (
	"fmt"
	"maps"
	"net/url"
	"path/filepath"
	"regexp"
	"slices"
	"strings"

	"github.com/prateep-r/mek/internal/config"
	"github.com/prateep-r/mek/internal/fsutil"
)

// AWS wraps the aws CLI v2.
//
// For SSO contexts mek generates its own AWS config file
// (~/.config/mek/aws/config) and points AWS_CONFIG_FILE at it, so the user's
// ~/.aws/config is never modified. Credentials stay in the AWS CLI's own SSO
// token cache (~/.aws/sso/cache) — mek never stores access keys.
type AWS struct {
	cfg *config.Config
	ctx *config.Context
	dir string
}

// Static credentials in the environment would silently win over the profile.
var awsUnset = []string{
	"AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_SESSION_TOKEN",
	"AWS_SECURITY_TOKEN", "AWS_DEFAULT_PROFILE",
}

func (a *AWS) CLI() string { return "aws" }

func ProfileName(ctx string) string { return "mek-" + ctx }

func (a *AWS) configPath() string { return filepath.Join(a.dir, "aws", "config") }

func (a *AWS) profile() string {
	if a.ctx.AWSProfile != "" {
		return a.ctx.AWSProfile
	}
	return ProfileName(a.ctx.Name)
}

func (a *AWS) Prepare() (Env, error) {
	env := Env{Set: map[string]string{"AWS_PROFILE": a.profile()}, Unset: awsUnset}
	if a.ctx.Region != "" {
		env.Set["AWS_REGION"] = a.ctx.Region
		env.Set["AWS_DEFAULT_REGION"] = a.ctx.Region
	}
	if a.ctx.AWSProfile != "" {
		return env, nil // use the user's own ~/.aws/config untouched
	}
	if err := WriteAWSConfig(a.configPath(), a.cfg); err != nil {
		return env, err
	}
	env.Set["AWS_CONFIG_FILE"] = a.configPath()
	return env, nil
}

// WriteAWSConfig renders every SSO context into one AWS config file.
// Contexts with the same start URL share one [sso-session], so a single
// `mek login` covers all accounts behind that portal.
func WriteAWSConfig(path string, cfg *config.Config) error {
	var b strings.Builder
	b.WriteString("# Generated by mek — do not edit; changes are overwritten.\n")
	sessions := map[string]*config.Context{}
	for _, name := range cfg.Names() {
		c := cfg.Contexts[name]
		if !c.IsSSO() {
			continue
		}
		s := SessionName(c.SSOStartURL)
		sessions[s] = c
		fmt.Fprintf(&b, "\n[profile %s]\nsso_session = %s\nsso_account_id = %s\nsso_role_name = %s\n",
			ProfileName(name), s, c.AccountID, c.Role)
		if c.Region != "" {
			fmt.Fprintf(&b, "region = %s\n", c.Region)
		}
		b.WriteString("output = json\n")
	}
	for _, s := range slices.Sorted(maps.Keys(sessions)) {
		c := sessions[s]
		fmt.Fprintf(&b, "\n[sso-session %s]\nsso_start_url = %s\nsso_region = %s\nsso_registration_scopes = sso:account:access\n",
			s, c.SSOStartURL, c.SSORegionOrDefault())
	}
	return fsutil.WriteFileAtomic(path, []byte(b.String()), 0o600)
}

var nonAlnum = regexp.MustCompile(`[^a-z0-9]+`)

// SessionName derives a stable sso-session name from a start URL,
// e.g. https://my-org.awsapps.com/start -> mek-my-org.
func SessionName(startURL string) string {
	host := startURL
	if u, err := url.Parse(startURL); err == nil && u.Host != "" {
		host = u.Host
	}
	host = strings.TrimSuffix(strings.ToLower(host), ".awsapps.com")
	return "mek-" + strings.Trim(nonAlnum.ReplaceAllString(host, "-"), "-")
}

func (a *AWS) LoginCommands(bool) [][]string {
	return [][]string{{"aws", "sso", "login", "--profile", a.profile()}}
}

func (a *AWS) WhoAmICommand() []string {
	return []string{"aws", "sts", "get-caller-identity", "--output", "table"}
}

func (a *AWS) Describe() string {
	if a.ctx.AWSProfile != "" {
		return fmt.Sprintf("aws profile %s", a.ctx.AWSProfile)
	}
	region := a.ctx.Region
	if region == "" {
		region = "-"
	}
	return fmt.Sprintf("aws %s / %s / %s", a.ctx.AccountID, a.ctx.Role, region)
}
