package provider

import (
	"errors"
	"fmt"
	"maps"
	"net/url"
	"path/filepath"
	"regexp"
	"slices"
	"strings"

	"github.com/prateep-r/mek/internal/config"
	"github.com/prateep-r/mek/internal/fsutil"
	"github.com/prateep-r/mek/internal/guard"
)

var awsCloud = Cloud{
	Name: config.ProviderAWS, CLI: "aws", Title: "AWS CLI",
	New: func(cfg *config.Config, ctx *config.Context, dir string) Provider {
		return &AWS{cfg: cfg, ctx: ctx, dir: dir}
	},
	Classify:    guard.ClassifyAWS,
	Validate:    validateAWS,
	ValidateAll: validateSSOSessions,
	Tool: Tool{VersionArgs: []string{"--version"}, Brew: "brew install awscli",
		URL: "https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html"},
}

var accountID = regexp.MustCompile(`^[0-9]{12}$`)

// isSSO reports whether an AWS context logs in through IAM Identity Center
// (as opposed to reusing an existing aws_profile).
func isSSO(c *config.Context) bool { return c.Provider == config.ProviderAWS && c.AWSProfile == "" }

// ssoRegion is the IAM Identity Center region, defaulting to region.
func ssoRegion(c *config.Context) string {
	if c.SSORegion != "" {
		return c.SSORegion
	}
	return c.Region
}

func validateAWS(c *config.Context) error {
	if c.AWSProfile != "" {
		return nil
	}
	var missing []string
	for _, f := range []struct{ key, val string }{
		{"account_id", c.AccountID}, {"role", c.Role}, {"sso_start_url", c.SSOStartURL},
	} {
		if f.val == "" {
			missing = append(missing, f.key)
		}
	}
	if len(missing) > 0 {
		return fmt.Errorf("aws context needs aws_profile, or %s", strings.Join(missing, ", "))
	}
	if !accountID.MatchString(c.AccountID) {
		return fmt.Errorf("account_id must be 12 digits, got %q", c.AccountID)
	}
	if ssoRegion(c) == "" {
		return errors.New("aws sso context needs sso_region (or region)")
	}
	return nil
}

// validateSSOSessions: contexts on one portal share one [sso-session], which
// has one region.
func validateSSOSessions(cfg *config.Config) error {
	first := map[string]*config.Context{} // sso_start_url -> first context using it
	for _, name := range cfg.Names() {
		c := cfg.Contexts[name]
		if !isSSO(c) {
			continue
		}
		if f, ok := first[c.SSOStartURL]; !ok {
			first[c.SSOStartURL] = c
		} else if ssoRegion(f) != ssoRegion(c) {
			return fmt.Errorf("contexts %q and %q share sso_start_url %s but have different sso_region (%s vs %s)",
				f.Name, name, c.SSOStartURL, ssoRegion(f), ssoRegion(c))
		}
	}
	return nil
}

// AWS wraps the aws CLI v2.
//
// For SSO contexts mek generates its own AWS config file
// (~/.config/mek/aws/config) and points AWS_CONFIG_FILE at it, so the user's
// ~/.aws/config is never modified. Credentials stay in the AWS CLI's own SSO
// token cache (~/.aws/sso/cache) — mek never stores access keys.
type AWS struct {
	cfg *config.Config
	ctx *config.Context
	dir string
}

// Static credentials in the environment would silently win over the profile.
var awsUnset = []string{
	"AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_SESSION_TOKEN",
	"AWS_SECURITY_TOKEN", "AWS_DEFAULT_PROFILE",
}

func profileName(ctx string) string { return "mek-" + ctx }

func (a *AWS) configPath() string { return filepath.Join(a.dir, "aws", "config") }

func (a *AWS) profile() string {
	if a.ctx.AWSProfile != "" {
		return a.ctx.AWSProfile
	}
	return profileName(a.ctx.Name)
}

func (a *AWS) Prepare() (Env, error) {
	env := Env{Set: map[string]string{"AWS_PROFILE": a.profile()}, Unset: awsUnset}
	if a.ctx.Region != "" {
		env.Set["AWS_REGION"] = a.ctx.Region
		env.Set["AWS_DEFAULT_REGION"] = a.ctx.Region
	}
	if a.ctx.AWSProfile != "" {
		return env, nil // use the user's own ~/.aws/config untouched
	}
	if err := writeAWSConfig(a.configPath(), a.cfg); err != nil {
		return env, err
	}
	env.Set["AWS_CONFIG_FILE"] = a.configPath()
	return env, nil
}

// writeAWSConfig renders every SSO context into one AWS config file.
// Contexts with the same start URL share one [sso-session], so a single
// `mek login` covers all accounts behind that portal.
func writeAWSConfig(path string, cfg *config.Config) error {
	var b strings.Builder
	b.WriteString("# Generated by mek — do not edit; changes are overwritten.\n")
	sessions := map[string]*config.Context{}
	for _, name := range cfg.Names() {
		c := cfg.Contexts[name]
		if !isSSO(c) {
			continue
		}
		s := sessionName(c.SSOStartURL)
		sessions[s] = c
		fmt.Fprintf(&b, "\n[profile %s]\nsso_session = %s\nsso_account_id = %s\nsso_role_name = %s\n",
			profileName(name), s, c.AccountID, c.Role)
		if c.Region != "" {
			fmt.Fprintf(&b, "region = %s\n", c.Region)
		}
		b.WriteString("output = json\n")
	}
	for _, s := range slices.Sorted(maps.Keys(sessions)) {
		c := sessions[s]
		fmt.Fprintf(&b, "\n[sso-session %s]\nsso_start_url = %s\nsso_region = %s\nsso_registration_scopes = sso:account:access\n",
			s, c.SSOStartURL, ssoRegion(c))
	}
	return fsutil.WriteFileAtomic(path, []byte(b.String()), 0o600)
}

var nonAlnum = regexp.MustCompile(`[^a-z0-9]+`)

// sessionName derives a stable sso-session name from a start URL,
// e.g. https://my-org.awsapps.com/start -> mek-my-org.
func sessionName(startURL string) string {
	host := startURL
	if u, err := url.Parse(startURL); err == nil && u.Host != "" {
		host = u.Host
	}
	host = strings.TrimSuffix(strings.ToLower(host), ".awsapps.com")
	return "mek-" + strings.Trim(nonAlnum.ReplaceAllString(host, "-"), "-")
}

func (a *AWS) LoginCommands(bool) ([][]string, error) {
	return [][]string{{"aws", "sso", "login", "--profile", a.profile()}}, nil
}

func (a *AWS) WhoAmICommand() []string {
	return []string{"aws", "sts", "get-caller-identity", "--output", "table"}
}

func (a *AWS) Describe() string {
	if a.ctx.AWSProfile != "" {
		return fmt.Sprintf("aws profile %s", a.ctx.AWSProfile)
	}
	return fmt.Sprintf("aws %s / %s / %s", a.ctx.AccountID, a.ctx.Role, orDash(a.ctx.Region))
}
